version: '3.8'

services:
  server:
    build: ./server
    volumes:
      - ./server/public:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
